# Site Info
title:              "Scrivener"
description:        "The Plain is a Minimalist Jekyll theme that focuses on writing matters."
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-72505907-1

# Author Info
author_name:        "telemachus"
author_email:       hnrird@gmail.com
author_gravatar:    http://www.gravatar.com/avatar/2b38b1b0e7e08b69379bd61582adf0c8.png
twitter_username:   telemachus77

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
